apiVersion: apps/v1
kind: Deployment
metadata:
  name: effluo-flask
  namespace: effluo
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: navojith/effluo-flask:latest
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: effluo-flask-env
---
apiVersion: v1
kind: Service
metadata:
  name: effluo-flask
  namespace: effluo
spec:
  selector:
    app: flask
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
  type: NodePort
